const PREFIX = 'CSS_PROP'

export const CHANGE_PROPERTY = `${PREFIX}:CHANGE_PROPERTY`
export const CHANGE_SIGN = `${PREFIX}:CHANGE_SIGN`
export const CHANGE_COMPARATOR = `${PREFIX}:CHANGE_COMPARATOR`
export const CHANGE_TEXT = `${PREFIX}:CHANGE_TEXT`

