const PREFIX = 'COOKIE'

export const CHANGE_COOKIE = `${PREFIX}:CHANGE_COOKIE`
export const CHANGE_SIGN = `${PREFIX}:CHANGE_SIGN`
export const CHANGE_COMPARATOR = `${PREFIX}:CHANGE_COMPARATOR`
export const CHANGE_TEXT = `${PREFIX}:CHANGE_TEXT`

